[package]
name = "ea"
version = "0.1.0"
edition = "2018"

[dependencies]
atty = '0.2.14'
bincode = '1.3.3'
clap = { version = "3.1.8", features = ["derive"] }
lazy_static = '1.4'
pty = '0.2'
regex = '1'
serde = { version = "1.0", features = ["derive"] }
