[package]
name = "ea"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = '1.3.3'
clap = { version = "3.1.8", features = ["derive"] }
pty = '0.2'
serde = { version = "1.0", features = ["derive"] }
